export const ActionTypes = {
  ADD_PIN: "ADD_PIN",
  ADD_ROPE: "ADD_ROPE",
  TOGGLE_TOOL: "TOGGLE_TOOL",
  MOVE_ITEM: "MOVE_ITEM",
  MOVE_NODE: "MOVE_NODE",
  REMOVE_ITEM: "REMOVE_ITEM",
  SELECT_ITEM: "SELECT_ITEM",
  UNSELECT_ITEM: "UNSELECT_ITEM",
};
