export const ActionTypes = {
  ADD_PHOTOS: "ADD_PHOTOS",
  ADD_PIN: "ADD_PIN",
  ADD_ROPE: "ADD_ROPE",
  CLEAR_BOARD: "CLEAR_BOARD",
  TOGGLE_TOOL: "TOGGLE_TOOL",
  MOVE_ITEM: "MOVE_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  SELECT_ITEM: "SELECT_ITEM",
  UPDATE_KNOT: "UPDATE_KNOT",
  UNSELECT_ITEM: "UNSELECT_ITEM",
};
